# Generated by Django 3.1.12 on 2025-04-23 15:32

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=djongo.models.fields.JSONField(default=list),
        ),
    ]
